name: js floss license check

on:
  push:
    branches:
      - main
      - alpha
      - beta
    paths:
      - 'src/Finos.Fdc3.Backplane.Client.JS/package.json'
      - 'src/Finos.Fdc3.Backplane.Client.JS/package-lock.json'
      - '.github/workflows/node-license-scanning.yml'
  pull_request:
    branches:
      - main
      - alpha
      - beta
    paths:
      - 'src/Finos.Fdc3.Backplane.Client.JS/package.json'
      - 'src/Finos.Fdc3.Backplane.Client.JS/package-lock.json'
      - '.github/workflows/node-license-scanning.yml'

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: npm ci --omit dev
        working-directory: src/Finos.Fdc3.Backplane.Client.JS
      - run: npm install -g node-license-validator
        working-directory: src/Finos.Fdc3.Backplane.Client.JS
      - run: node-license-validator . --allow-licenses Apache-2.0 MIT BSD-2-Clause BSD BSD-3-Clause Unlicense
        working-directory: src/Finos.Fdc3.Backplane.Client.JS
