name: js cve checks
on: 
  push:
    branches:
      - main
      - alpha
      - beta
    paths:
      - 'src/Finos.Fdc3.Backplane.Client.JS/package.json'
      - 'src/Finos.Fdc3.Backplane.Client.JS/package-lock.json'
      - 'src/Finos.Fdc3.Backplane.Client.JS/allow-list.json'
      - '.github/workflows/node-cve-scanning.yml'
  pull_request:
    branches:
      - main
      - alpha
      - beta
    paths:
      - 'src/Finos.Fdc3.Backplane.Client.JS/package.json'
      - 'src/Finos.Fdc3.Backplane.Client.JS/package-lock.json'
      - 'src/Finos.Fdc3.Backplane.Client.JS/allow-list.json'
      - '.github/workflows/node-cve-scanning.yml'

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: npm ci --omit dev
        working-directory: src/Finos.Fdc3.Backplane.Client.JS
      - run: npx --yes auditjs ossi --whitelist allow-list.json
        working-directory: src/Finos.Fdc3.Backplane.Client.JS
