name: npm release
on:
  push:
    branches:
      - main
      - alpha
      - beta
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js 
        uses: actions/setup-node@v3
        with:
           node-version: latest
           cache: 'npm'
           cache-dependency-path: '**/package-lock.json'
           
      - name: Package install
        run: npm ci
        working-directory: ./src/Finos.Fdc3.Backplane.Client.JS
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: vivek-natwest  
          GIT_AUTHOR_EMAIL: vivek.kumargiri@natwestmarkets.com
          GIT_COMMITTER_NAME: vivek-natwest
          GIT_COMMITTER_EMAIL: vivek.kumargiri@natwestmarkets.com
        run: npx semantic-release
        working-directory: ./src/Finos.Fdc3.Backplane.Client.JS
