name: npm build
on:
  push:
  pull_request:
    branches:
      - main
      - alpha

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - name: Package install
      run: npm ci
      working-directory: ./src/Finos.Fdc3.Backplane.Client.JS
    - name: Build
      run: npm run build
      working-directory: ./src/Finos.Fdc3.Backplane.Client.JS
  
