name: nuget release
on:
  push:
    branches:
      - main
      - alpha
      - beta
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src/Finos.Fdc3.Backplane.Client

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
          node-version: latest
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          
    - name: Package install
      run: npm ci
      working-directory: ./src/Finos.Fdc3.Backplane.Client

    - name: Release
      env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.AUTO_RELEASE_TOKEN }}
          GIT_AUTHOR_NAME: manish-nwm  
          GIT_AUTHOR_EMAIL: manish.bhutani@natwestmarkets.com
          GIT_COMMITTER_NAME: manish-nwm
          GIT_COMMITTER_EMAIL: manish.bhutani@natwestmarkets.com
      run: npx semantic-release 
      working-directory: ./src/Finos.Fdc3.Backplane.Client
